pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "yourdockerhubusername/my-app"
    }

    stages {

        stage('Build') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE .'
            }
        }

        stage('Login to DockerHub') {
            steps {
                withCredentials([string(credentialsId: 'dockerhub-password', variable: 'DOCKER_PASS')]) {
                    sh 'echo $DOCKER_PASS | docker login -u yourdockerhubusername --password-stdin'
                }
            }
        }

        stage('Push') {
            steps {
                sh 'docker push $DOCKER_IMAGE'
            }
        }

        stage('Deploy') {
            steps {
                sh 'kubectl apply -f kubernetes_manifest/deployment.yaml'
            }
        }
    }
}